using UnityEngine;
using System.Collections;

public class Firetrap : MonoBehaviour
{
    [SerializeField] private float damage;

    [Header("Firetrap Timers")]
    [SerializeField] private float activationDelay;
    [SerializeField] private float activeTime;
    private Animator anim;
    private SpriteRenderer spriteRend;

    private bool triggered; //when the trap gets triggered
    private bool active; //when the trap is active and can hurt the player

    [Header("FireTrap Sound")]
    [SerializeField] private AudioClip FireTrapSound;
private void Start()
{
    anim = GetComponent<Animator>();
    spriteRend = GetComponent<SpriteRenderer>();

    // Controlla se il componente SpriteRenderer Ã¨ presente prima di utilizzarlo
    if (spriteRend != null)
    {
        // Avvia la coroutine ActivateFiretrap al momento dell'avvio
        StartCoroutine(ActivateFiretrap());
    }
    else
    {
        Debug.LogError("SpriteRenderer non trovato su " + gameObject.name);
    }
}

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.tag == "Player")
        {
            if (!triggered)
                StartCoroutine(ActivateFiretrap());

            if (active)
                collision.GetComponent<Health>().TakeDamage(damage);
        }
    }

    private IEnumerator ActivateFiretrap()
    {
        //turn the sprite red to notify the player and trigger the trap
        triggered = true;
        spriteRend.color = Color.red;

        //Wait for delay, activate trap, turn on animation, return color back to normal
        yield return new WaitForSeconds(activationDelay);
        SoundManager.instance.PlaySound(FireTrapSound);
        spriteRend.color = Color.white; //turn the sprite back to its initial color
        active = true;
        anim.SetBool("activated", true);

        //Wait until X seconds, deactivate trap and reset all variables and animator
        yield return new WaitForSeconds(activeTime);
        active = false;
        triggered = false;
        anim.SetBool("activated", false);
    }
}
